// MASSIVE keyword list (EN / ES / DE / KO) for practical “covers almost everything” matching.
// Notes:
// - Keep keywords mostly lowercase because you do: exerciseName.toLowerCase().
// - For Spanish/German accents, I include BOTH accented + unaccented variants.
// - I intentionally put more specific phrases first, and generic ones later.
// - If you keep very generic words like "press", "row", "curl", "extension", expect more false-positives.
//   (But you asked “as long as possible”, so they’re included near the end.)

export const MUSCLE_KEYWORDS: Record<string, string[]> = {
  chest: [
    // =======================
    // ENGLISH (CHEST)
    // =======================
    'bench press',
    'barbell bench press',
    'bb bench press',
    'dumbbell bench press',
    'db bench press',
    'flat bench press',
    'incline bench press',
    'decline bench press',
    'close grip bench press', // (can overlap triceps; keep special-cased if needed)
    'wide grip bench press',
    'paused bench press',
    'touch and go bench',
    'floor press',
    'dumbbell floor press',
    'guillotine press',
    'spoto press',
    'board press',
    'smith bench press',
    'smith machine bench press',
    'machine bench press',
    'chest press',
    'machine chest press',
    'seated chest press',
    'standing chest press',
    'incline chest press',
    'decline chest press',
    'plate loaded chest press',
    'hammer strength chest press',
    'converging chest press',
    'iso lateral chest press',
    'cable chest press',
    'cable press',
    'single arm cable press',
    'one arm cable press',
    'pec fly',
    'pec flye',
    'chest fly',
    'chest flye',
    'dumbbell fly',
    'dumbbell flye',
    'incline dumbbell fly',
    'incline fly',
    'decline fly',
    'cable fly',
    'cable flye',
    'low to high cable fly',
    'high to low cable fly',
    'mid cable fly',
    'cable crossover',
    'cable cross over',
    'crossover',
    'cross over',
    'cable cross',
    'cable crossovers',
    'standing cable crossover',
    'single arm crossover',
    'one arm crossover',
    'pec deck',
    'pec-deck',
    'peck deck',
    'pectoral deck',
    'butterfly machine',
    'butterfly',
    'machine fly',
    'machine flye',
    'chest dip',
    'leaning dip',
    'forward dip',
    'ring dip',
    'push up',
    'push-up',
    'pushup',
    'press up',
    'press-up',
    'pressup',
    'incline push up',
    'decline push up',
    'diamond push up', // (overlaps triceps)
    'wide push up',
    'weighted push up',
    'weighted push-up',
    'ring push up',
    'deficit push up',
    'archer push up',
    'pseudo planche push up',
    'planche lean push up',
    'squeeze press',
    'svend press',
    'hex press',
    'dumbbell squeeze press',
    'isometric chest squeeze',
    'chest squeeze',
    'pullover',
    'dumbbell pullover',
    'db pullover',
    'cable pullover', // (can overlap back; but common chest)
    'straight arm pullover',
    'chest',
    'pec',
    'pecs',
    'pectoral',
    'pectorals',
    'upper chest',
    'lower chest',

    // Common abbreviations / variants
    'bench',
    'bb bench',
    'db bench',
    'incline bench',
    'decline bench',
    'flat bench',
    'incline db bench',
    'decline db bench',
    'smith bench',
    'smith press (bench)',
    'chest machine',
    'chest press machine',

    // =======================
    // SPANISH (PECHO)
    // =======================
    'press de banca',
    'press banca',
    'banca',
    'press en banca',
    'press de banca plano',
    'press de banca inclinado',
    'press de banca declinado',
    'press plano',
    'press inclinado',
    'press declinado',
    'press con barra',
    'press con mancuernas',
    'press mancuernas',
    'press en máquina',
    'press en maquina',
    'press en smith',
    'press en multipower',
    'press pecho',
    'press de pecho',
    'press de pecho en maquina',
    'press de pecho en máquina',
    'press sentado de pecho',
    'press de pecho inclinado',
    'press de pecho declinado',
    'press en polea',
    'press en poleas',
    'press con cable',
    'press a una mano en polea',
    'press unilateral en polea',
    'aperturas',
    'aperturas con mancuernas',
    'aperturas en banco',
    'aperturas inclinadas',
    'aperturas declinadas',
    'aperturas en polea',
    'aperturas en poleas',
    'aperturas con cable',
    'cruce de poleas',
    'cruce poleas',
    'cruce en poleas',
    'cruce en polea',
    'cruce de cables',
    'cruce de cable',
    'crossover',
    'pec deck',
    'peck deck',
    'contractora',
    'contractor',
    'mariposa',
    'máquina de mariposa',
    'maquina de mariposa',
    'fondos',
    'fondos en paralelas',
    'fondos pecho',
    'fondos para pecho',
    'fondos inclinados',
    'flexiones',
    'flexión',
    'flexiones de pecho',
    'flexiones inclinadas',
    'flexiones declinadas',
    'flexiones abiertas',
    'flexiones con peso',
    'flexiones lastradas',
    'lagartijas',
    'pullover',
    'pullover con mancuerna',
    'pullover con mancuernas',
    'pecho',
    'pectoral',
    'pectorales',
    'parte superior del pecho',
    'pecho superior',
    'pecho inferior',

    // Accentless duplicates (for messy inputs)
    'máquina',
    'maquina',
    'flexión',
    'flexion',

    // =======================
    // GERMAN (BRUST)
    // =======================
    'bankdrücken',
    'bankdruecken',
    'flachbankdrücken',
    'flachbankdruecken',
    'schrägbankdrücken',
    'schraegbankdruecken',
    'schrägbank drücken',
    'schraegbank druecken',
    'negativbankdrücken',
    'negativbankdruecken',
    'kurzhantel bankdrücken',
    'kurzhantel bankdruecken',
    'langhantel bankdrücken',
    'langhantel bankdruecken',
    'bankdrücken lh',
    'bankdruecken lh',
    'bankdrücken kh',
    'bankdruecken kh',
    'floor press',
    'brustpresse',
    'maschine brustpresse',
    'chest press',
    'schmetterling',
    'butterfly',
    'butterfly maschine',
    'pec deck',
    'fliegende',
    'fliegende kh',
    'kabelzug fly',
    'kabelzug flys',
    'kabelzug überkreuz',
    'kabelzug ueberkreuz',
    'kabel überkreuz',
    'kabel ueberkreuz',
    'cable crossover',
    'dips brust',
    'liegestütz',
    'liegestuetze',
    'liegestütze',
    'push up',
    'push-up',
    'pullover',
    'überzüge',
    'ueberzuege',
    'brust',
    'brustmuskel',
    'brustmuskeln',
    'oberbrust',
    'unterbrust',

    // =======================
    // KOREAN (가슴)
    // =======================
    '벤치프레스',
    '벤치 프레스',
    '바벨 벤치프레스',
    '덤벨 벤치프레스',
    '인클라인 벤치프레스',
    '디클라인 벤치프레스',
    '플랫 벤치프레스',
    '스미스 벤치프레스',
    '체스트프레스',
    '체스트 프레스',
    '머신 체스트프레스',
    '머신 체스트 프레스',
    '케이블 체스트프레스',
    '케이블 프레스',
    '푸쉬업',
    '푸시업',
    '팔굽혀펴기',
    '인클라인 푸쉬업',
    '디클라인 푸쉬업',
    '딥스',
    '가슴 딥스',
    '플라이',
    '덤벨 플라이',
    '인클라인 플라이',
    '케이블 플라이',
    '크로스오버',
    '케이블 크로스오버',
    '케이블 크로스',
    '펙덱',
    '버터플라이',
    '풀오버',
    '가슴',
    '흉근',
    '상부 가슴',
    '하부 가슴',

    // =======================
    // VERY GENERIC (risky) — keep LAST
    // =======================
    'press', // huge overlap
    'chest press', // ok-ish
    'fly', // overlap rear delt fly
    'flye',
    'dip', // overlap triceps
  ],

  back: [
    // =======================
    // ENGLISH (BACK)
    // =======================
    'lat pulldown',
    'lat pull down',
    'wide grip lat pulldown',
    'close grip lat pulldown',
    'neutral grip lat pulldown',
    'underhand lat pulldown',
    'overhand lat pulldown',
    'single arm lat pulldown',
    'one arm lat pulldown',
    'straight arm pulldown',
    'straight-arm pulldown',
    'straight arm pull down',
    'cable pulldown',
    'pulldown',
    'pull down',
    'pullup',
    'pull up',
    'pull-up',
    'wide grip pull up',
    'close grip pull up',
    'neutral grip pull up',
    'chin up',
    'chin-up',
    'chinup',
    'neutral grip chin up',
    'assisted pull up',
    'assisted pull-up',
    'row',
    'rows',
    'barbell row',
    'bb row',
    'dumbbell row',
    'db row',
    'one arm row',
    'single arm row',
    'kroc row',
    'meadows row',
    'seal row',
    'pendlay row',
    'bent over row',
    'bent-over row',
    'chest supported row',
    'chest-supported row',
    'machine row',
    'hammer strength row',
    'cable row',
    'seated cable row',
    'seated row',
    'low row',
    'high row',
    't bar row',
    't-bar row',
    'landmine row',
    'inverted row',
    'bodyweight row',
    'australian pull up',
    'australian pull-up',
    'face pull',
    'rear delt row', // overlap shoulders/back
    'shrug',
    'shrugs',
    'deadlift',
    'conventional deadlift',
    'sumo deadlift',
    'romanian deadlift', // overlap legs
    'rdl',
    'rack pull',
    'block pull',
    'deficit deadlift',
    'good morning',
    'hyperextension',
    'hyper extension',
    'back extension',
    'reverse hyper',
    'cobra row', // rare
    'lat',
    'lats',
    'latissimus',
    'upper back',
    'mid back',
    'lower back',
    'back',
    'trap',
    'traps',
    'trapezius',

    // =======================
    // SPANISH (ESPALDA)
    // =======================
    'jalón',
    'jalon',
    'jalón al pecho',
    'jalon al pecho',
    'jalón en polea',
    'jalon en polea',
    'jalón dorsal',
    'jalon dorsal',
    'polea al pecho',
    'jalón agarre ancho',
    'jalón agarre estrecho',
    'jalón agarre neutro',
    'jalón supino',
    'jalón prono',
    'jalón unilateral',
    'jalón a una mano',
    'pulldown',
    'dominadas',
    'dominada',
    'dominada asistida',
    'dominadas asistidas',
    'chin up',
    'remo',
    'remos',
    'remo con barra',
    'remo con mancuerna',
    'remo mancuerna',
    'remo a una mano',
    'remo unilateral',
    'remo en polea',
    'remo en polea baja',
    'remo sentado',
    'remo bajo',
    'remo alto',
    'remo t',
    'remo en t',
    'remo landmine',
    'remo invertido',
    'face pull',
    'encogimientos',
    'encogimiento',
    'trapecio',
    'peso muerto',
    'peso muerto convencional',
    'peso muerto sumo',
    'peso muerto rumano',
    'rdl',
    'rack pull',
    'buenos días',
    'buenos dias',
    'hiperextensiones',
    'hiperextension',
    'extensión lumbar',
    'extension lumbar',
    'extensiones de espalda',
    'espalda',
    'dorsal',
    'dorsales',
    'lats',
    'zona lumbar',
    'lumbar',

    // =======================
    // GERMAN (RÜCKEN)
    // =======================
    'latzug',
    'weiter latzug',
    'enger latzug',
    'neutraler latzug',
    'untergriff latzug',
    'obergriff latzug',
    'einarmiger latzug',
    'klimmzug',
    'klimmzuege',
    'klimmzüge',
    'chin-up',
    'rudern',
    'ruderzug',
    'kabelrudern',
    'sitzendes rudern',
    'low row',
    't-bar rudern',
    't-bar row',
    'landmine rudern',
    'umgekehrtes rudern',
    'face pull',
    'shrugs',
    'schulterheben', // shrug
    'kreuzheben',
    'konventionelles kreuzheben',
    'sumo kreuzheben',
    'rumänisches kreuzheben',
    'rumaenisches kreuzheben',
    'rdl',
    'rack pulls',
    'good morning',
    'hyperextension',
    'rückenstrecker',
    'rueckenstrecker',
    'rücken',
    'ruecken',
    'lats',
    'trapez',
    'trapezius',
    'nacken', // traps/upper back

    // =======================
    // KOREAN (등)
    // =======================
    '랫풀다운',
    '래트풀다운',
    '풀다운',
    '랫 풀다운',
    '케이블 풀다운',
    '스트레이트 암 풀다운',
    '풀업',
    '턱걸이',
    '친업',
    '로우',
    '바벨 로우',
    '덤벨 로우',
    '원암 로우',
    '케이블 로우',
    '시티드 로우',
    '티바로우',
    '랜드마인 로우',
    '인버티드 로우',
    '페이스풀',
    '슈러그',
    '데드리프트',
    '랙풀',
    '루마니안 데드리프트',
    '굿모닝',
    '백 익스텐션',
    '하이퍼익스텐션',
    '등',
    '광배',
    '광배근',
    '승모',
    '상부 등',
    '하부 등',
    '허리',

    // =======================
    // VERY GENERIC (risky) — keep LAST
    // =======================
    'row',
    'pulldown',
    'pull down',
    'back',
    'lat',
  ],

  legs: [
    // =======================
    // ENGLISH (LEGS)
    // =======================
    'back squat',
    'front squat',
    'high bar squat',
    'low bar squat',
    'box squat',
    'pause squat',
    'goblet squat',
    'hack squat',
    'safety bar squat',
    'ssb squat',
    'zercher squat',
    'pistol squat',
    'split squat',
    'bulgarian split squat',
    'bulgarian',
    'walking lunge',
    'reverse lunge',
    'forward lunge',
    'side lunge',
    'lateral lunge',
    'curtsy lunge',
    'step up',
    'step-up',
    'leg press',
    'sled press',
    'horizontal leg press',
    '45 degree leg press',
    'hack press',
    'belt squat',
    'hip thrust',
    'barbell hip thrust',
    'glute bridge',
    'single leg glute bridge',
    'hamstring curl',
    'leg curl',
    'lying leg curl',
    'seated leg curl',
    'standing leg curl',
    'nordic curl',
    'nordic ham curl',
    'glute ham raise',
    'ghr',
    'leg extension',
    'quad extension',
    'sissy squat',
    'reverse nordic',
    'calf raise',
    'standing calf raise',
    'seated calf raise',
    'donkey calf raise',
    'tibialis raise',
    'adductor',
    'abductor',
    'hip abduction',
    'hip adduction',
    'sumo deadlift', // overlap back
    'romanian deadlift', // overlap back
    'rdl',
    'good morning', // overlap back
    'glute',
    'glutes',
    'hamstring',
    'hamstrings',
    'quad',
    'quads',
    'calf',
    'calves',
    'leg',
    'legs',
    'lower body',

    // =======================
    // SPANISH (PIERNAS)
    // =======================
    'sentadilla',
    'sentadilla trasera',
    'sentadilla frontal',
    'sentadilla pausa',
    'sentadilla goblet',
    'sentadilla hack',
    'sentadilla sissy',
    'sentadilla zercher',
    'sentadilla búlgara',
    'sentadilla bulgara',
    'zancada',
    'zancadas',
    'zancada caminando',
    'zancada inversa',
    'zancada lateral',
    'desplante',
    'desplantes',
    'step up',
    'subida al cajón',
    'subida al cajon',
    'prensa',
    'prensa de piernas',
    'prensa 45',
    'cinturón squat',
    'belt squat',
    'hip thrust',
    'empuje de cadera',
    'puente de glúteo',
    'puente de gluteo',
    'curl femoral',
    'curl de piernas',
    'curl acostado',
    'curl sentado',
    'curl de isquios',
    'nordic curl',
    'curl nordico',
    'glute ham raise',
    'extensión de piernas',
    'extension de piernas',
    'extensión de cuádriceps',
    'extension de cuadriceps',
    'elevación de gemelos',
    'elevacion de gemelos',
    'gemelo',
    'gemelos',
    'tibial',
    'abductores',
    'aductores',
    'abducción',
    'abduccion',
    'aducción',
    'aduccion',
    'glúteo',
    'gluteo',
    'glúteos',
    'gluteos',
    'femoral',
    'isquios',
    'isquiotibial',
    'cuádriceps',
    'cuadriceps',
    'pierna',
    'piernas',
    'tren inferior',

    // =======================
    // GERMAN (BEINE)
    // =======================
    'kniebeuge',
    'frontkniebeuge',
    'boxkniebeuge',
    'pausekniebeuge',
    'goblet knieugebe',
    'goblet kniebeuge',
    'hackenschmidt',
    'hack squat',
    'zercher knieugebe',
    'zercher kniebeuge',
    'pistol squat',
    'ausfallschritt',
    'ausfallschritte',
    'walking lunges',
    'seitlicher ausfallschritt',
    'beinpresse',
    'bein presse',
    '45 grad beinpresse',
    'belt squat',
    'hip thrust',
    'glute bridge',
    'beinbeuger',
    'beincurl',
    'bein curl',
    'liegender beinbeuger',
    'sitzender beinbeuger',
    'nordic curl',
    'beinstrecker',
    'bein strecker',
    'wadenheben',
    'stehendes wadenheben',
    'sitzendes wadenheben',
    'tibialis',
    'adduktor',
    'abduktor',
    'adduktion',
    'abduktion',
    'gesäß',
    'gesaess',
    'gluteus',
    'quadrizeps',
    'hamstrings',
    'wade',
    'waden',
    'bein',
    'beine',
    'unterkörper',
    'unterkoerper',

    // =======================
    // KOREAN (하체)
    // =======================
    '스쿼트',
    '백 스쿼트',
    '프론트 스쿼트',
    '박스 스쿼트',
    '포즈 스쿼트',
    '고블릿 스쿼트',
    '핵스쿼트',
    '불가리안',
    '불가리안 스플릿 스쿼트',
    '피스톨 스쿼트',
    '런지',
    '워킹 런지',
    '리버스 런지',
    '사이드 런지',
    '스텝업',
    '레그프레스',
    '레그 프레스',
    '힙쓰러스트',
    '힙 쓰러스트',
    '글루트 브리지',
    '레그 컬',
    '레그컬',
    '햄스트링 컬',
    '노르딕 컬',
    'GHR',
    '레그 익스텐션',
    '레그익스텐션',
    '카프 레이즈',
    '카프레이즈',
    '스탠딩 카프 레이즈',
    '시티드 카프 레이즈',
    '티비알리스 레이즈',
    '애덕터',
    '어브덕터',
    '하체',
    '다리',
    '둔근',
    '엉덩이',
    '햄스트링',
    '대퇴',
    '대퇴사두',
    '쿼드',
    '종아리',

    // =======================
    // VERY GENERIC (risky)
    // =======================
    'squat',
    'lunge',
    'leg',
    'extension',
    'curl',
  ],

  shoulders: [
    // =======================
    // ENGLISH (SHOULDERS)
    // =======================
    'overhead press',
    'ohp',
    'standing overhead press',
    'seated overhead press',
    'military press',
    'shoulder press',
    'dumbbell shoulder press',
    'barbell shoulder press',
    'smith shoulder press',
    'machine shoulder press',
    'arnold press',
    'push press',
    'strict press',
    'behind the neck press',
    'behind-the-neck press',
    'upright row',
    'high pull', // overlap oly
    'lateral raise',
    'side raise',
    'dumbbell lateral raise',
    'cable lateral raise',
    'machine lateral raise',
    'front raise',
    'dumbbell front raise',
    'plate front raise',
    'cable front raise',
    'rear delt raise',
    'rear deltoid raise',
    'rear delt fly',
    'rear delt flye',
    'reverse fly',
    'reverse flye',
    'reverse pec deck',
    'reverse pec-deck',
    'rear delt machine',
    'face pull', // overlap back but common for rear delts
    'cuban press',
    'cuban rotation',
    'external rotation',
    'shoulder',
    'shoulders',
    'deltoid',
    'deltoids',
    'delt',
    'delts',
    'rear delt',
    'side delt',
    'front delt',

    // =======================
    // SPANISH (HOMBROS)
    // =======================
    'press militar',
    'press militar de pie',
    'press militar sentado',
    'press hombro',
    'press de hombro',
    'press de hombros',
    'press sobre la cabeza',
    'press overhead',
    'press trasnuca',
    'trasnuca',
    'press arnold',
    'arnold press',
    'elevaciones laterales',
    'elevación lateral',
    'elevacion lateral',
    'elevaciones frontales',
    'elevación frontal',
    'elevacion frontal',
    'pájaro',
    'pajaro',
    'aperturas inversas',
    'reverse fly',
    'reverse flye',
    'face pull',
    'remo al mentón',
    'remo al menton',
    'upright row',
    'press cubano',
    'cuban press',
    'rotación externa',
    'rotacion externa',
    'hombro',
    'hombros',
    'deltoides',
    'deltoide',
    'deltoides posterior',
    'deltoide posterior',

    // =======================
    // GERMAN (SCHULTER)
    // =======================
    'schulterdrücken',
    'schulterdruecken',
    'überkopfdrücken',
    'ueberkopfdruecken',
    'überkopf press',
    'ueberkopf press',
    'military press',
    'arnold press',
    'nackendrücken',
    'nackendruecken',
    'seitheben',
    'frontheben',
    'reverse fly',
    'reverse butterfly',
    'butterfly reverse',
    'face pull',
    'aufrrechtes rudern',
    'aufrechtes rudern',
    'upright row',
    'cuban press',
    'außenrotation',
    'aussenrotation',
    'schulter',
    'schultern',
    'deltoid',
    'deltoide',

    // =======================
    // KOREAN (어깨)
    // =======================
    '오버헤드 프레스',
    '밀리터리 프레스',
    '숄더프레스',
    '숄더 프레스',
    '덤벨 숄더프레스',
    '바벨 숄더프레스',
    '머신 숄더프레스',
    '아놀드 프레스',
    '푸시 프레스',
    '비하인드 넥 프레스',
    '업라이트 로우',
    '레터럴 레이즈',
    '사이드 레이즈',
    '프론트 레이즈',
    '리어 델트',
    '리어 델트 플라이',
    '리버스 플라이',
    '리버스 펙덱',
    '페이스풀',
    '큐반 프레스',
    '외회전',
    '어깨',
    '숄더',
    '델트',
    '델토이드',

    // =======================
    // VERY GENERIC (risky)
    // =======================
    'overhead',
    'military',
    'lateral',
    'raise',
  ],

  arms: [
    // =======================
    // ENGLISH (ARMS)
    // =======================
    'bicep curl',
    'biceps curl',
    'barbell curl',
    'ez bar curl',
    'ez-bar curl',
    'straight bar curl',
    'dumbbell curl',
    'alternating dumbbell curl',
    'incline dumbbell curl',
    'incline curl',
    'hammer curl',
    'cross body hammer curl',
    'preacher curl',
    'machine preacher curl',
    'spider curl',
    'concentration curl',
    'cable curl',
    'rope cable curl',
    'bayesian curl',
    'drag curl',
    'reverse curl',
    'wrist curl',
    'reverse wrist curl',
    'forearm curl',
    'farmer curl', // rare naming
    'tricep extension',
    'triceps extension',
    'overhead tricep extension',
    'overhead triceps extension',
    'dumbbell tricep extension',
    'cable tricep extension',
    'rope tricep extension',
    'tricep pushdown',
    'triceps pushdown',
    'rope pushdown',
    'straight bar pushdown',
    'v-bar pushdown',
    'skullcrusher',
    'skull crusher',
    'lying tricep extension',
    'french press',
    'jm press',
    'close grip bench press', // overlaps chest
    'close-grip bench press',
    'diamond push up', // overlaps chest
    'kickback',
    'tricep kickback',
    'triceps kickback',
    'dips triceps',
    'tricep dip',
    'bicep',
    'biceps',
    'tricep',
    'triceps',
    'arm',
    'arms',
    'forearm',
    'forearms',

    // =======================
    // SPANISH (BRAZOS)
    // =======================
    'curl biceps',
    'curl bíceps',
    'curl biceps con barra',
    'curl bíceps con barra',
    'curl con barra',
    'curl con mancuernas',
    'curl alterno',
    'curl inclinado',
    'curl martillo',
    'martillo',
    'curl predicador',
    'predicador',
    'curl araña',
    'curl concentrado',
    'concentrado',
    'curl en polea',
    'curl polea',
    'curl bayesiano',
    'curl reverso',
    'curl invertido',
    'curl muñeca',
    'curl muneca',
    'antebrazo',
    'extensión de tríceps',
    'extension de triceps',
    'extensión tríceps',
    'extension triceps',
    'extensión de tríceps por encima',
    'extension triceps por encima',
    'jalón de tríceps',
    'jalon de triceps',
    'pushdown',
    'rompecráneos',
    'rompecraneos',
    'press francés',
    'press frances',
    'jm press',
    'agarre cerrado',
    'press cerrado',
    'patada',
    'patada de tríceps',
    'patada de triceps',
    'bíceps',
    'biceps',
    'tríceps',
    'triceps',
    'brazo',
    'brazos',

    // =======================
    // GERMAN (ARME)
    // =======================
    'bizeps curl',
    'bizepscurls',
    'langhantel curls',
    'kurzhantel curls',
    'sz curls',
    'ez curls',
    'hammercurl',
    'preacher curl',
    'konzentrationscurl',
    'kabel curls',
    'reverse curl',
    'unterarm',
    'handgelenkcurls',
    'trizepsdrücken',
    'trizepsdruecken',
    'trizeps extension',
    'überkopf trizeps',
    'ueberkopf trizeps',
    'pushdown',
    'seil pushdown',
    'stirndrücken',
    'stirndruecken',
    'skullcrusher',
    'french press',
    'kickbacks',
    'bizeps',
    'trizeps',
    'arm',
    'arme',

    // =======================
    // KOREAN (팔)
    // =======================
    '이두',
    '이두근',
    '바이셉',
    '바이셉스',
    '컬',
    '바벨 컬',
    '덤벨 컬',
    '얼터네이팅 컬',
    '인클라인 컬',
    '해머 컬',
    '크로스바디 해머 컬',
    '프리처 컬',
    '스파이더 컬',
    '컨센트레이션 컬',
    '케이블 컬',
    '베이지안 컬',
    '리버스 컬',
    '전완',
    '손목 컬',
    '삼두',
    '삼두근',
    '트라이셉',
    '트라이셉스',
    '스컬크러셔',
    '트라이셉스 익스텐션',
    '오버헤드 트라이셉스 익스텐션',
    '푸쉬다운',
    '로프 푸쉬다운',
    '킥백',
    '클로즈그립 벤치',
    '다이아몬드 푸쉬업',
    '팔',

    // =======================
    // VERY GENERIC (risky)
    // =======================
    'curl',
    'extension',
    'pushdown',
  ],

  core: [
    // =======================
    // ENGLISH (CORE)
    // =======================
    'ab wheel',
    'ab-wheel',
    'ab rollout',
    'ab roll out',
    'rollout',
    'roll out',
    'crunch',
    'crunches',
    'cable crunch',
    'machine crunch',
    'sit up',
    'sit-up',
    'situp',
    'v up',
    'v-up',
    'vup',
    'hollow hold',
    'hollow body hold',
    'dead bug',
    'dead-bug',
    'leg raise',
    'lying leg raise',
    'hanging leg raise',
    'knee raise',
    'hanging knee raise',
    'toes to bar',
    'toes-to-bar',
    't2b',
    'russian twist',
    'bicycle crunch',
    'mountain climber',
    'plank',
    'front plank',
    'side plank',
    'plank side',
    'pallof press',
    'woodchopper',
    'wood chopper',
    'cable woodchopper',
    'cable wood chopper',
    'core',
    'abs',
    'ab',
    'abdominal',
    'abdominals',

    // =======================
    // SPANISH (CORE)
    // =======================
    'rueda abdominal',
    'rueda de abdominales',
    'ab wheel',
    'rollout',
    'crunch',
    'crunches',
    'crunch en polea',
    'abdominales',
    'abdominal',
    'sit up',
    'sit-up',
    'v-up',
    'v up',
    'hollow',
    'bicho muerto',
    'dead bug',
    'elevación de piernas',
    'elevacion de piernas',
    'elevación de rodillas',
    'elevacion de rodillas',
    'toes to bar',
    'russian twist',
    'giros rusos',
    'bicicleta',
    'abdominal bicicleta',
    'escalador',
    'mountain climber',
    'plancha',
    'plancha frontal',
    'plancha lateral',
    'pallof press',
    'leñador',
    'lenador',
    'woodchopper',
    'core',

    // =======================
    // GERMAN (CORE)
    // =======================
    'bauch',
    'bauchmuskeln',
    'crunch',
    'crunches',
    'kabel crunch',
    'sit-up',
    'sit up',
    'v-up',
    'hollow hold',
    'dead bug',
    'beinheben',
    'hängendes beinheben',
    'haengendes beinheben',
    'kniebeheben',
    'toes to bar',
    'russian twist',
    'fahrrad',
    'mountain climber',
    'plank',
    'seitstütz',
    'seitstuetz',
    'side plank',
    'pallof press',
    'woodchopper',
    'bauchrolle',
    'ab wheel',
    'rollout',
    'core',

    // =======================
    // KOREAN (코어)
    // =======================
    '코어',
    '복근',
    '복부',
    '크런치',
    '케이블 크런치',
    '싯업',
    '브이업',
    'v-up',
    '할로우 홀드',
    '데드버그',
    '레그 레이즈',
    '행잉 레그 레이즈',
    '니 레이즈',
    '행잉 니 레이즈',
    '토즈 투 바',
    't2b',
    '러시안 트위스트',
    '바이시클 크런치',
    '마운틴 클라이머',
    '플랭크',
    '사이드 플랭크',
    '팔로프 프레스',
    '우드초퍼',
    'ab 휠',
    'ab휠',
    '롤아웃',

    // =======================
    // VERY GENERIC (risky)
    // =======================
    'plank',
    'crunch',
  ],
};

// (Optional) If you want to reduce false positives WITHOUT changing much:
// - Remove generic tokens: "press", "row", "curl", "extension", "raise" from the lists above.
// - Or keep them only if no “high confidence” match occurs.

export function detectMuscleGroup(exerciseName: string): string {
  if (!exerciseName) return 'unknown';
  const lowerName = exerciseName.toLowerCase().trim();

  // Special cases / disambiguation
  if (lowerName.includes('shoulder') || lowerName.includes('hombro') || lowerName.includes('schulter') || lowerName.includes('어깨') || lowerName.includes('lateral raise')) return 'shoulders';
  if (lowerName.includes('squat') || lowerName.includes('sentadilla') || lowerName.includes('kniebeuge') || lowerName.includes('스쿼트') || lowerName.includes('leg ext') || lowerName.includes('leg curl') || lowerName.includes('leg press') || lowerName.includes('calf') || lowerName.includes('adduction') || lowerName.includes('hip thrust')) return 'legs';
  if (lowerName.includes('bench') || lowerName.includes('banca') || lowerName.includes('bank') || lowerName.includes('벤치') || lowerName.includes('chest press')) return 'chest';
  if (lowerName.includes('deadlift') || lowerName.includes('peso muerto') || lowerName.includes('kreuzheben') || lowerName.includes('데드리프트') || lowerName.includes('row') || lowerName.includes('pull up') || lowerName.includes('lat pulldown')) return 'back';
  if (lowerName.includes('curl') || lowerName.includes('tricep') || lowerName.includes('bicep') || lowerName.includes('arm')) return 'arms';
  if (lowerName.includes('crunch') || lowerName.includes('plank') || lowerName.includes('abdominal') || lowerName.includes('core')) return 'core';

  // General iteration
  for (const [muscle, keywords] of Object.entries(MUSCLE_KEYWORDS)) {
    for (const keyword of keywords) {
      if (lowerName.includes(keyword)) {
        return muscle;
      }
    }
  }

  return 'unknown';
}

